"""add minio storage fields

Revision ID: f9211c70bae7
Revises: 754d8fdef922
Create Date: 2026-06-18 19:55:33.739464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9211c70bae7'
down_revision: Union[str, Sequence[str], None] = '754d8fdef922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('bucket_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'bucket_name')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
